jordansingleton@Jordans-MBP-3 ~ % dusty up
Pulling latest updates for all active managed repos:
Compiling together the assembled specs
Ensuring virtualbox vm is running
Virtual machine boot2docker-vm already exists
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/jordansingleton/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/jordansingleton/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/jordansingleton/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/jordansingleton/.boot2docker/certs/boot2docker-vm

rsync is already installed!
192.168.59.103
Compiling the port specs
Compiling the nginx config
Compiling docker-compose config
Saving port forwarding to hosts file
Syncing local repos to the VM
Syncing overridden repo github.com/gamechanger/gcstatengine to remote at /persist/repos/github.com/gamechanger/gcstatengine
Syncing overridden repo github.com/gamechanger/gclib to remote at /persist/repos/github.com/gamechanger/gclib
Syncing overridden repo github.com/gamechanger/puffin to remote at /persist/repos/github.com/gamechanger/puffin
Saving nginx config and ensure nginx is running
Saving docker-compose config and starting all containers
Recreating dusty_coreRedis_1...
Creating dusty_coreMongo_1...
Pulling image mongo:2.6.9...
Pulling repository mongo
Traceback (most recent call last):
File "<string>", line 3, in <module>
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
File "/compose/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Get https://index.docker.io/v1/repositories/library/mongo/images: dial tcp: lookup index.docker.io on 71.243.0.12:53: read udp 71.243.0.12:53: i/o timeout
Your local environment is now started
